apiVersion: v1
kind: Service
metadata:
# Nome do serviço (permitirá a comunicação com outros deployments)
  name: mysql-service
spec:
# Tipo de configuração da service
  type: ClusterIP
  selector:
  # Especifica o deployment que está sendo referenciado. Deve ser o mesmo valor contido em "spec.selector.matchLabels.app" do deployment
    app: mysql-deployment
  ports:
  - port: 3306
  # Utilizado quando o service é configurado com o "type: NodePort"
    # targetPort: <Target Port> 

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
# O type LoadBalancer é responsável pela comunicação com o mundo externo
  type: LoadBalancer
  selector:
    app: wordpress-deployment
  ports:
  - port: 80
    # targetPort: <Target Port>
