apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress-deployment
  template:
    metadata:
      labels:
        app: wordpress-deployment
    spec:
      containers:
      - name: wordpress-image
        image: wordpress:4.8-apache
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
          # Host do banco de dados dentro do kubernetes
            value: mysql-deployment
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
              # Nome da secret
                name: mysql-secret
                # Nome da key dentro da secret
                key: password
        volumeMounts:
        # Nome do volume a ser criado
          - name: wordpress-volume
          # path que será gravado as informações de disco
            mountPath: /var/www/html
      volumes:
      # Deve ser o mesmo nome de "volumeMounts"
        - name: wordpress-volume
          persistentVolumeClaim:
          # Nome do volume criado em PersistentVolumeClaim
            claimName: wordpress-pvc